config/routes.rb
Rails.application.routes.draw do
  resources :problems
  get 'sessions/new'

  get 'welcome/index'
  root 'welcome#index'

  get '/what_is_a_ctf',     to: 'welcome#what_is_a_ctf'
  get '/about',             to: 'welcome#about'
  get '/signup',            to: 'users#new'
  post '/signup',           to: 'users#create'
  get '/login',             to: 'sessions#new'
  post '/login',            to: 'sessions#create'
  delete '/logout',         to: 'sessions#destroy'
  resources :users
  get '/problems',          to: 'problems#index'
  get '/problems',          to: 'problems#new'
  post '/problems/submit/:id',     to: 'problems#submit'
  resources :problems           

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    
    before_save{ self.email = email.downcase }

    validates :name, presence: true, length: {maximum: 60}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
        format: { with: VALID_EMAIL_REGEX }, 
        uniqueness: { case_sensitive: false}
    
    has_secure_password
    validates :password, presence: true, length: { minimum: 6}    
    
# Returns the hash digest
def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? Bcrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost

    BCrypt::Passsword.create(string, cost:cost)
end
                                        
# Returns a random token

def User.new_token
    SecureRandom.urlsafe_base64
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem1 = Problem.new
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def submit 
    
    @correct_problem = Problem.find(params[:id])
    x = @correct_problem.total_submissions + 1
    @correct_problem.update(total_submissions: x)

    if @correct_problem.flag == params[:problem][:flag]
      redirect_to problem_url, notice: 'Flag is correct!'
      y = @correct_problem.successful_submissions + 1
      @correct_problem.update(successful_submissions: y)
    else 
      redirect_to problem_url, notice: 'Flag is incorrect!'
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:problem_id, :problem_statement, :flag, :supp_file, :upvote_downvote, :max_points, :successful_submissions, :total_submissions, :dirty_bit)
    end

    


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
      #Log the user in
    else
      flash.now[:danger] = 'Invalid email / password combination' 
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #Handle a successful save
      log_in @user
      UserMailer.welcome_email(@user).deliver_now
      flash[:success] = "Sign up Successful! Welcome to CaptureTF!"
      redirect_to @user
      
    else
      render 'new'

    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def what_is_a_ctf
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user] = user
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper

    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaptureTF</title>
    <%= csrf_meta_tags %>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Capture TF!</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a class="ListItem" href="/what_is_a_ctf" >What is a CTF?</a></li>
        <li><a class="ListItem" href="/problems">Challenges</a></li>
        <li><a class="ListItem" href="/about">About</a></li>
        <li><a class="ListItem" href="https://ctftime.org/" target="_blank">CTFtime</a></li>
        <li><a class="ListItem" href="/login">Login</a></li>
        <li><a class="ListItem" href="/signup">Signup</a></li>
      </ul>
    </div>
  </div>
</nav>
    <div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    Aditi Gupta, Adwaith Gautham <%= Time.now.year %>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/problems/_form.html.erb
<%= form_with(model: problem, local: true) do |form| %>
  <% if problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :problem_id %>
    <%= form.number_field :problem_id, id: :problem_problem_id %>
  </div>

  <div class="field">
    <%= form.label :problem_statement %>
    <%= form.text_area :problem_statement, id: :problem_problem_statement %>
  </div>

  <div class="field">
    <%= form.label :flag %>
    <%= form.text_area :flag, id: :problem_flag %>
  </div>

  <div class="field">
    <%= form.label :supp_file %>
    <%= form.text_area :supp_file, id: :problem_supp_file %>
  </div>

  <div class="field">
    <%= form.label :upvote_downvote %>
    <%= form.number_field :upvote_downvote, id: :problem_upvote_downvote %>
  </div>

  <div class="field">
    <%= form.label :max_points %>
    <%= form.number_field :max_points, id: :problem_max_points %>
  </div>

  <div class="field">
    <%= form.label :successful_submissions %>
    <%= form.number_field :successful_submissions, id: :problem_successful_submissions %>
  </div>

  <div class="field">
    <%= form.label :total_submissions %>
    <%= form.number_field :total_submissions, id: :problem_total_submissions %>
  </div>

  <div class="field">
    <%= form.label :dirty_bit %>
    <%= form.check_box :dirty_bit, id: :problem_dirty_bit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Problems</h1>

<table class="table">
  <thead>
    <tr>
      <th>Problem</th>
      <th>Problem statement</th>      
      <th>Max points</th>
      <th>Successful submissions</th>
      <th>Total submissions</th>
      
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= problem.problem_id %></td>
        <td><%= problem.problem_statement %></td>
        <td><%= problem.max_points %></td>
        <td><%= problem.successful_submissions %></td>
        <td><%= problem.total_submissions %></td>
       
        <td><%= link_to 'Show', problem %></td>
        <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
        <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a New Problem', new_problem_path %>

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Problem:</strong>
  <%= @problem.problem_id %>
</p>

<p>
  <strong>Problem statement:</strong>
  <%= @problem.problem_statement %>
</p>

<p>
  <strong>Supp file:</strong>
  <%= @problem.supp_file %>
</p>

<p>
  <strong>Upvote downvote:</strong>
  <%= @problem.upvote_downvote %>
</p>

<p>
  <strong>Max points:</strong>
  <%= @problem.max_points %>
</p>

<p>
  <strong>Successful submissions:</strong>
  <%= @problem.successful_submissions %>
</p>

<p>
  <strong>Total submissions:</strong>
  <%= @problem.total_submissions %>
</p>

<p>
  <strong>Enter your flag:</strong>
</p>
<%= form_for @problem1, :url => { :action => "submit"} do |f| %>
  <%= f.text_area(:flag, size: '50x10') %>
  <%= f.submit "Submit Flag",  class: "btn btn-primary" %>
<% end %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question id</th>
      <th>Problem name</th>
      <th>Max points</th>
      <th>Submissions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.Question_ID %></td>
        <td><%= question.Problem_Name %></td>
        <td><%= question.Max_Points %></td>
        <td><%= question.Submissions %></td>
        <td><a href="/questions/show">Show</a></td>
        <td><a href="/questions/edit">Edit</a></td>
        <td><a href="/questions/destroy">Destroy</a></td>
        
        <%# <td><%= link_to 'Show', question_path %></td> %> 
        <%# <td><%= link_to 'Edit', edit_question_path(question) %></td> %> 
        <%# <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td> %> %>
       
       </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
        
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
  </br>
</br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1> Welcome! Your signup was successful!</h1>
            <h1>
               <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>

app/views/welcome/about.html.erb
<html>
    <body background-image: url(/app/assets/images/gravel.png)>

        <h2>This CTF Practice Platform is developed by :<br><br>
        Aditi Gupta (16CO202) and Adwaith Gautham (16CO203)<br>Third Year, B.Tech., Department of Computer Science and Engineering<br>NITK Surathkal <br><br>as a part of coursework for CO303: Database Management Systems Lab.</h2>
    </body>
</html>

app/views/welcome/index.html.erb
<html>
    <body>
        <h1>Hello fellow hackers! Welcome to CaptureTF!</h1>
        <h2>This is a platform where you can practice questions on different fields:<br><br></h2>
        <h3>
        Reverse Engineering<br>
        Pwning<br>
        Web Exploitation<br>
        Forensics<br>
        And much more!<br>
        </h3><br>
        <h2>If you want to hone your hacking skills, then you have come to the right place!</h2>
    </body>
</html>

app/views/welcome/what_is_a_ctf.html.erb
<html>
    <head>
        <title>What is a CTF?</title>
    </head>
    <body>
        <h1>What is a CTF?</h1>
        <h3>CTF (Capture The Flag) is a competition where one solves various challenges from different fields of Computer Security. The competition can happen in 2 styles.
        <br><br>
        <b>Jeopardy:</b> In this CTF style, there will be several challenges under each category and you solve them to get points. These are the popular categories: 
<br><br>Web Vulnerabilities and Exploitation
<br>Reverse Engineering
<br>Binary Exploitation
<br>Cryptography
<br>Digital Forensics
<br>Miscellaneous 

<br><br>  <b>Attack-Defense:</b> In this CTF style, there will be 2 teams - the Red Team and Blue Team. A huge System consisting of various websites, softwares, networks will be given to both teams. The Red Team should attack the System. More number of successful attacks, more the points they get. On the other hand, the Blue Team is responsible of defending the attacks. They have  to patch up the System in order to get more points. 

 
        </h3>

        <h1>What do the categories mean?</h1>
        <h3>
            <b> Web Vulnerabilities and Exploitation:</b> Explores different Website / backend related vulnerabilities. A few examples are Cross Site Scripting, HTML Injection, Javascript Injection, Cross-site Request Forgery, SQL Injection, Cookie Hijacking, etc., 
<br><br>
<b> Reverse Engineering:</b> This involves challenges where one has to extract the algorithm or the source code of the complete program from a given executable / binary. Example: A malware sample is identified and it is using a specific Domain-Generation Algorithm. Given the sample, we have to find out what that algorithm is. 
<br><br>
<b> Binary Exploitation:</b> This category involves challenges related Software Security. Different vulnerabilities and exploit methods are explored. Example: Consider the Buffer Overflow Vulnerability. There are different exploit methods like Shellcode Injection, Ret2Libc, Return Oriented Programming, 2-stage Shellcode etc., 
<br><br>
<b> Cryptography:</b>There are different encryption and decryption algorithms, hashing algorithms, key-exchange algorithms. There are many weaknesses in many of the currently used algorithms. So, challenges generally focus on the weakness of a cryptographic algorithm and the method used to exploit it. 
<br><br>
<b>Digital Forensics:</b> Challenges of this category will be related to the work done by an Incident Response Team. Example: Suppose our NITK-NET got affected by a malware and the whole network is down. All that we have is the .pcap file(Network Capture). We have to identify and extract the malware, clean and patch our systems. 
<br><br>
<b> Miscellaneous: </b>There could be programming challenges, Combination of a few of the above categories, challenges from Steganography etc., 
<br><br>
</h3>
    </body>
</html>